FROM golang:1.27-alpine

RUN apk add --no-cache git make protobuf-dev

RUN go install github.com/air-verse/air@latest && \
    go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest && \
    go install golang.org/x/tools/cmd/goimports@latest && \
    go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080
